import * as inputSet from "./model/InputSet";
const formConfig = {
  firstName: new inputSet.InputSet(
    "firstName",
    "First name",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Valid first name is required.",
    "",
    "col-md-6 mb-3"
  ),
  lastName: new inputSet.InputSet(
    "lastName",
    "Last name",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Valid last name is required.",
    "",
    "col-md-6 mb-3"
  ),
  username: new inputSet.InputSet(
    "username",
    "Username",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Your username is required.",
    "@",
    "mb-3"
  ),
  email: new inputSet.InputSet(
    "email",
    "Email",
    inputSet.EInputType.EMAIL,
    "form-control",
    "",
    "",
    true,
    "Please enter a valid email address for shipping updates.",
    "",
    "mb-3"
  ),
  address: new inputSet.InputSet(
    "address",
    "Address",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Please enter your shipping address.",
    "",
    "mb-3"
  ),
  address2: new inputSet.InputSet(
    "address2",
    "Address 2",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    false,
    "",
    "",
    "mb-3"
  ),
  country: new inputSet.SelectSet(
    "country",
    "Country",
    inputSet.EInputType.SELECT,
    "form-control",
    "",
    "",
    true,
    "Please select a valid country.",
    "mb-3",
    [
      { value: "0", label: "Select country", selected: true },
      { value: "United States", label: "United States", selected: false },
      { value: "Canada", label: "Canada", selected: false },
      { value: "Mexico", label: "Mexico", selected: false },
    ]
  ),
  state: new inputSet.SelectSet(
    "state",
    "State",
    inputSet.EInputType.SELECT,
    "form-control",
    "",
    "",
    true,
    "Please provide a valid state.",
    "mb-3",
    [
      { value: "0", label: "Select state", selected: true },
      { value: "California", label: "California", selected: false },
      { value: "Nevada", label: "Nevada", selected: false },
      { value: "Oregon", label: "Oregon", selected: false },
    ]
  ),
  zip: new inputSet.InputSet(
    "zip",
    "Zip",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Zip code required.",
    "",
    "mb-3"
  ),
  paymentMethods: [
    new inputSet.RadioButtonField(
      "credit",
      "Credit card",
      inputSet.EInputType.RADIO,
      "custom-control-input",
      "",
      "",
      false,
      "Please select a valid payment method.",
      "custom-control custom-radio",
      [],
      "paymentMethod"
    ),
    new inputSet.RadioButtonField(
      "debit",
      "Debit card",
      inputSet.EInputType.RADIO,
      "custom-control-input",
      "",
      "",
      false,
      "Please select a valid payment method.",
      "custom-control custom-radio",
      [],
      "paymentMethod"
    ),
    new inputSet.RadioButtonField(
      "paypal",
      "PayPal",
      inputSet.EInputType.RADIO,
      "custom-control-input",
      "",
      "",
      false,
      "Please select a valid payment method.",
      "custom-control custom-radio",
      [],
      "paymentMethod"
    ),
  ],
  nameOnCard: new inputSet.InputSet(
    "cc-name",
    "Name on card",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Name on card is required",
    "",
    "col-md-6 mb-3"
  ),
  creditCardNumber: new inputSet.InputSet(
    "cc-number",
    "Credit card number",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Credit card number is required",
    "",
    "col-md-6 mb-3"
  ),
  expiration: new inputSet.InputSet(
    "cc-expiration",
    "Expiration",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Expiration date required",
    "",
    "col-md-3 mb-3"
  ),
  cvv: new inputSet.InputSet(
    "cc-cvv",
    "CVV",
    inputSet.EInputType.TEXT,
    "form-control",
    "",
    "",
    true,
    "Security code required",
    "",
    "col-md-3 mb-3"
  ),
  checkOptionSet: [
    new inputSet.CheckboxField(
      "same-address",
      "Shipping address is the same as my billing address",
      inputSet.EInputType.CHECKBOX,
      "form-check-input",
      "",
      "",
      false,
      "",
      "custom-control custom-checkbox"
    ),
    new inputSet.CheckboxField(
      "save-info",
      "Save this information for next time",
      inputSet.EInputType.CHECKBOX,
      "form-check-input",
      "",
      "",
      false,
      "",
      "custom-control custom-checkbox"
    ),
  ],
};

export default formConfig;
